export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';
export const AJAX_CALL_SUCCESS = 'AJAX_CALL_SUCCESS';

export const GET_LIST_CHAR = 'GET_LIST_CHAR';

export const GET_FILM = 'GET_FILM';
export const CLEAR_FILM = 'CLEAR_FILM';

export const GET_HOMEWORLD = 'GET_HOMEWORLD';
export const CLEAN_HOMEWORLD = 'CLEAN_HOMEWORLD';

export const GET_SPECIES = 'GET_SPECIES';
export const CLEAN_SPECIES = 'CLEAN_SPECIES';

export const GET_VEHICLE = 'GET_VEHICLE';
export const CLEAN_VEHICLE = 'CLEAN_VEHICLE';

export const GET_STARSHIP = 'GET_STARSHIP';
export const CLEAN_STARSHIP = 'CLEAN_STARSHIP';